name = "demo"
version = "0.1.0"
target = "javascript"


[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
lustre = ">= 5.2.1 and < 6.0.0"
lustre_ui = { path = "../" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.8.2 and < 2.0.0"
