name = "backend"
version = "1.0.0"

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
