name: deep-space-nine-rta-chart
services:
  postgres:
    image: postgres:17-bookworm
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - CLAUDE_CONFIG_DIR=/home/node/.claude
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - DATABASE_URL=postgresql://user:passw0rd@postgres:5432/app_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passw0rd
    init: true
    ipc: host
    ports:
      - "9323:9323"
    tty: true
    user: node
    volumes:
      - ../:/workspace:delegated
      - claude-code-config:/home/node/.claude
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: postgres_data-${COMPOSE_PROJECT_NAME:-default}
    driver: local
  claude-code-config:
    name: claude-code-config-${COMPOSE_PROJECT_NAME:-default}
    driver: local
